Pipeline:
  name: foo

GitRepo:
  name: sampleRepo
  gitProvider: myGitIntegration
  path: jfrog/jfrog-pipelines
  branches:
    include: {{gitBranch}}

artifactoryIntegration: myArtIntegration

Image:
  name: sampleImage
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: sampleBuild
  dockerImageName: pipelines.jfrog.io/templates-docker-local/dbp
  dockerFileName: Dockerfile
  dockerFileLocation: './.jfrog-pipelines/template-DockerBuildAndPush'
  dockerImageTag: ${run_number}

DockerPush:
  name: samplePush
  targetRepository: templates-target-local

BuildInfo:
  autoPublishBuildInfo: true
  name: sampleBuildInfo
